application: tompiere
version: 2
runtime: python
api_version: 1

handlers:

- url: /
  static_files: index.html
  upload: index.html

- url: /TomPiere.docx
  static_files: TomPiere.docx
  upload: TomPiere.docx

- url: /(.*)
  static_files: \1
  upload: (.*)

- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

- url: /fonts
  static_dir: fonts

- url: /
  static_dir: fonts